### ISSUE TITLE
Inscription et authentification

### ISSUE THREAD

**Issue by ThomasEscorne** [cyril-cordier/tc95us#2]
Il ne semble rien se passer quand je remplis le formulaire d'inscription et que je clique sur "S'enregistrer", pas plus de succès avec les pages de login

**Comment by cyril-cordier** [comment]
Problème réglé, un champ obligatoire dans la DB manquait dans le formulaire d'enregistrement.

**Comment by cyril-cordier** [comment]
Problème réglé, un champ obligatoire dans la DB manquait dans le formulaire d'enregistrement.
